name: "Deploy da Aplicação"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug - Show IMAGE_NAME
        run: |
          echo "Image Name: ${{ secrets.DOCKER_HUB_IMAGE }}"

      - name: Pull Docker Image (latest tag)
        run: docker pull ${{ secrets.DOCKER_HUB_IMAGE }}:latest

      - name: Stop Existing Docker Container (if running)
        run: docker stop serenity || true

      - name: Remove Existing Docker Container (if exists)
        run: docker rm serenity || true

      - name: Create Google Forms Credentials File
        run: |
          # Garante que o diretório seja criado/existente com permissões adequadas
          sudo mkdir -p /tmp/google_forms_creds
          # Remove qualquer arquivo/diretório existente com privilégios elevados
          sudo rm -rf /tmp/google_forms_creds/google-forms-api-credentials.json
          # Escreve o conteúdo no arquivo usando sudo tee para permissão de escrita
          echo "${{ secrets.GOOGLE_FORMS_CREDENTIALS_JSON }}" | sudo tee /tmp/google_forms_creds/google-forms-api-credentials.json > /dev/null
        env:
          GOOGLE_FORMS_CREDENTIALS_JSON: ${{ secrets.GOOGLE_FORMS_CREDENTIALS_JSON }}

      - name: Run New Docker Container
        run: |
          docker run \
            --name serenity \
            -d \
            -p 8080:8080 \
            --restart=always \
            -v /tmp/google_forms_creds/google-forms-api-credentials.json:/app/secret/google-forms-api-credentials.json \
            -e ACC_NAME=${{ secrets.ACC_NAME }} \
            -e ACC_KEY=${{ secrets.ACC_KEY }} \
            -e ACC_CONTAINER_NAME=${{ secrets.ACC_CONTAINER_NAME }} \
            -e DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
            -e SQL_SENHA=${{ secrets.SQL_SENHA }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }} \
            -e EMAIL_SENHA=${{ secrets.EMAIL_SENHA }} \
            -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            -e AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
            -e AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }} \
            -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }} \
            -e GOOGLE_FORMS_API_CREDENTIALS_PATH=/app/secret/google-forms-api-credentials.json \
            ${{ secrets.DOCKER_HUB_IMAGE }}:latest
