name: "Exemplo de CD"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Garanta que seu runner está online e configurado para o repositório ou grupo com acesso a ele

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Show IMAGE_NAME
        run: echo "Image Name: ${{ secrets.IMAGE_NAME }}"

      - name: Pull Docker image
        run: docker pull ${{ secrets.IMAGE_NAME }}:latest

      - name: Stop Docker container
        run: docker stop serenity || true

      - name: Remove Docker container
        run: docker rm serenity || true

      - name: Run Docker container
        run: docker run --name serenity -d -p 8080:8080 --restart=always ${{ secrets.IMAGE_NAME }}:latest
