name: "Exemplo de CD"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # Certifique-se que seu runner está online e configurado para o repositório ou grupo com acesso a ele

    steps:
      - name: Debug - Show IMAGE_NAME
        # Indentação: 4 espaços antes de 'run:' em relação a '- name:'
        run: echo "Image Name: ${{ secrets.IMAGE_NAME }}"

      - name: Pull Docker image
        run: docker pull ${{ secrets.IMAGE_NAME }}:latest

      - name: Stop Docker container
        run: docker stop serenity || true

      - name: Remove Docker container
        run: docker rm serenity || true

      - name: Run Docker container
        # Adiciona --restart=always para reiniciar automaticamente
        run: docker run --name serenity -d -p 8080:8080 --restart=always ${{ secrets.IMAGE_NAME }}:latest
